name: Build iOS IPA
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Xcode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'

      - name: Force Stable .NET Version
        run: |
          echo '{"sdk": {"version": "9.0.100", "rollForward": "minor"}}' > global.json

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.100'

      - name: Install and Restore MAUI Workloads
        run: |
          dotnet workload install maui --from-rollback-file https://aka.ms || dotnet workload install maui
          dotnet workload restore OpenUtauMobile/OpenUtauMobile.csproj

      - name: Build and Publish Unsigned
        run: |
          dotnet publish OpenUtauMobile/OpenUtauMobile.csproj -c Release -f net9.0-ios /p:ArchiveOnBuild=true /p:RuntimeIdentifier=ios-arm64 /p:WarningLevel=0 /p:ValidateXcodeVersion=false /p:CodesignKey="-" /p:CodesignProvision="-" /p:CompileAppManifest=false /p:EnableAppIconAssets=false /p:OptimizePNGs=false /p:BuildIpa=true
          
      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: OpenUtauMobile-IPA
          path: OpenUtauMobile/bin/Release/net9.0-ios/ios-arm64/publish/
