name: Build iOS IPA
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Install Mobile Workloads
        run: |
          dotnet workload install ios
          dotnet workload install android

      - name: Build and Publish
        run: |
          dotnet publish OpenUtauMobile/OpenUtauMobile.csproj -c Release -f net9.0-ios /p:ArchiveOnBuild=true /p:RuntimeIdentifier=ios-arm64

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: OpenUtauMobile-IPA
          path: OpenUtauMobile/bin/Release/net9.0-ios/ios-arm64/publish/
